services:
  drivenops_db:
    image: postgres
    container_name: drivenops_db
    restart: always
    ports:
      - "5532:5432"
    env_file:
      - .env.test
      
  drivenops_node_app:
    container_name: drivenops_node_app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - drivenops_db
    env_file:
      - .env.test
