on:
  push:
    branches: 
      - main
name: Build and Deploy
jobs: 
  build: 
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name:
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/Create-envfile@v1.3
        with: 
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "postgres"
          envkey_DATABASE_URL: "http://ec2-3-85-102-168.compute-1.amazonaws.com/api"
          directory: back-end/
          file_name: .env
          fail_on_empty: true

      - name: Create front-end env file
        uses: SpicyPizza/Create-envfile@v1.3
        with: 
          envkey_REACT_APP_BASE_URL: "postgresql://postgres:postgres@drivenops_db:5432/students"
          directory: front-end/
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose down && docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d