name: Pull request
on: [pull_request]
jobs: 
  PullRequest: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checar repositorio
        uses: actions/checkout@v3
      - name: fazer um novo arquivo env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.REACT_APP_BASE_URL_TEST}}
          file_name: .env.test
      - name: Rodar testes
        run: docker-compose -f docker-compose-tests.yml run drivenops_node_app npm run test




